[phases.setup]
nixPkgs = ["nodejs_20", "python311Full"]

[phases.install]
cmds = [
	"npm install",
	"python3 -m ensurepip --upgrade || true",
	"python3 -m pip --version",
	"python3 -m pip install --no-cache-dir piper-tts"
]

[phases.build]
cmds = ["echo 'no build step'"]

[start]
cmd = "bash start.sh"
